[target.x86_64-pc-windows-gnu]
linker = "C:/mingw64/bin/gcc.exe"
ar = "C:/mingw64/bin/ar.exe"

[env]
CC = "C:/mingw64/bin/gcc.exe"
AR = "C:/mingw64/bin/ar.exe"
OPENSSL_DIR = "C:/mingw64"
OPENSSL_STATIC = "1"
OPENSSL_LIB_DIR = "C:/mingw64/lib"
OPENSSL_INCLUDE_DIR = "C:/mingw64/include"
